server:
  servlet:
    context-path: /gestaofuncionarios/api

springdoc:
  swagger-ui:
    path: /swagger

spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb+srv://dev:root@desenvolvimento.cljnasy.mongodb.net/desenvolvimento?retryWrites=true&w=majority}
